apps/accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('welcome/', views.verified_merchant, name='verified-invite'),
    path('invalid-invite/', views.invalid_invite_merchant, name='invalid-invite'),
    path('uninvited/', views.uninvited_merchant, name='uninvited'),
    path('register/', views.register_merchant, name='register'),
    path('login/', views.login_merchant, name='login'),
    path('logout/', views.logout_merchant, name='logout'),
    path('register/verification/<str:user_id>/', views.email_verification, name='email-verification'),
    path('register/confirmation/<uidb64>/<token>/', views.email_confirmation, name='email-confirmation'),
    path('register/shop/', views.register_shop_information, name='merchant-add-shop'),
    path('register/logo/', views.register_shop_logo, name='merchant-add-logo'),
    path('register/settings/', views.register_shop_settings, name='merchant-add-settings'),
    path('register/deliveries/', views.register_shop_deliveries, name='merchant-add-delivery'),
    path('register/payment/', views.register_shop_account, name='merchant-add-payment'),
    path('shop/', views.edit_shop, name='shop'),
    path('shop/profile/', views.edit_shop_information, name='shop-profile'),
    path('shop/branding/', views.edit_shop_branding, name='shop-branding'),
    path('shop/general/', views.edit_shop_settings, name='shop-settings'),
    path('shop/deliveries/', views.edit_shop_deliveries, name='shop-delivery'),
    path('shop/payment/', views.edit_shop_account, name='shop-account'),
    path('account/', views.account_settings, name='account-settings'),
    path('notifications/', views.notification_settings, name='notification-settings'),
    path('notifications/save/', views.save_notification_settings, name='save-notification-settings'),
    path('resources/', views.resource_settings_faqs, name='resource-settings-faqs'),
    path('resources/feedback/', views.resource_settings_feedback, name='resource-settings-feedback'),
    path('resources/privacy-policy/', views.resource_settings_privacy_policy, name='resource-settings-privacy-policy'),
    path('resources/agreement/', views.resource_settings_agreement, name='resource-settings-agreement'),
    path('load_cities/', views.load_cities, name='load-cities'),
    path('load_times/', views.load_times, name='load-times'),
    path('load_pending_items', views.load_pending_items, name="load-items"),
    path('error-form/', views.error_form_submission, name='error-form'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
import accounts

# import debug_toolbar

urlpatterns = [
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    path('_nested_admin/', include('nested_admin.urls')),
    # url(r'^hijack/', include('hijack.urls', namespace='hijack')),
    path('accounts/', include('allauth.urls')),
    path('avatar/', include('avatar.urls')),
    path('', include(('accounts.urls', 'accounts'), namespace='users')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('finances/', include(('finances.urls', 'finances'), namespace='finances')),
]

if settings.LOCAL_DEV:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    handler400 = 'accounts.views.handler_400'
    handler403 = 'accounts.views.handler_403'
    handler404 = 'accounts.views.handler_404'
    handler500 = 'accounts.views.handler_500'

apps/accounts/models.py
from django.db import models
from django.utils.timezone import datetime, timedelta
from django.contrib.auth.models import UnicodeUsernameValidator, AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from .validators import only_int, exp_date

from imagekit import ImageSpec, register
from imagekit.processors import ResizeToFill, ResizeToFit
from model_utils.fields import MonitorField

import re


### Create your models here.
## Django Roles, Permissions, and Groups: https://medium.com/djangotube/django-roles-groups-and-permissions-introduction-a54d1070544
## Django Custom Authentication: https://docs.djangoproject.com/en/3.1/topics/auth/customizing/

##### SUMMARY OF ACCOUNT MODELS:
#### Super Admin — Quicklink High-Ranking Programmers (CRUD All)
### Admin — Quicklink Founders, High-Ranking Employees, and Programmers (CUD Some, R All)
## Staff — Quicklink Employees
# Merchants — Quicklink Clients / Users ()
# Customers — Customers of Quicklink Clients

class BaseAccountsModel(models.Model):
    class Meta:
        abstract = True
        app_label = 'accounts'

class MyUserManager(BaseUserManager):
    ## A custom user manager to deal with emails as unique identifiers for auth
    # instead of usernames. The default that's used is "UserManager"

    def _create_user(self, email, password, **extra_fields):
        # Creates and saves a User with the given email and password.
        if not email:
            raise ValueError('The email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)

    def get_merchants(self):
        return super().get_queryset().filter(role='MERCHANT')

    def get_customers(self):
        return super().get_queryset().filter(role='CUSTOMER')

class User(AbstractBaseUser, PermissionsMixin):
    class Types(models.TextChoices):
        SUPER_ADMIN = "SUPER_ADMIN", "Super Admin"
        ADMIN = "ADMIN", "Admin"
        QUICKIES = "QUICKIES", "Quickies"
        MERCHANT = "MERCHANT", "Merchant"
        CUSTOMER = "CUSTOMER", "Customer"

    role = models.CharField(_('role'), max_length=50, choices=Types.choices, default=Types.ADMIN, null=True)
    
    username = None
    email = models.EmailField(_("email address"), 
        max_length=150, 
        null=True, 
        unique=True,
        help_text=_("Please use a business email address."),
        error_messages={"unique": _("That email is already being used by another account."),},
    )

    password = models.CharField(max_length=150, null=True)

    device_id = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = MyUserManager()

    def __str__(self):
        if self.email:
            return f"{self.email}"
        elif self.device_id:
            return f"{self.device_id}"

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def get_initials(self):
        initials = []
        if hasattr(self, 'shop_info'):
            for name in list(self.shop_info.shop_name.split(' ')):
                initials.append(name[0])
            return ''.join(initials)
        elif hasattr(self, 'info_customer'):
            for name in list(self.info_customer.customer_name.split(' ')):
                initials.append(name[0])
            return ''.join(initials)
        else:
            return False

    class Meta:
        app_label = 'accounts'

# ACCOUNT INFORMATION
# Address
class Address(BaseAccountsModel):
    CITIES = [
        ("Caloocan City", _("Caloocan")),
        ("Las Piñas City", _("Las Piñas")),
        ("Makati City", _("Makati")),
        ("Malabon City", _("Malabon")),
        ("Malanduyong City", _("Malanduyong")),
        ("Manila City", _("Manila")),
        ("Marikina City", _("Marikina")),
        ("Muntinlupa City", _("Muntinlupa")),
        ("Navotas City", _("Navotas")),
        ("Parañaque City", _("Parañaque")),
        ("Pasay City", _("Pasay")),
        ("Pasig City", _("Pasig")),
        ("Pateros City", _("Pateros")),
        ("Quezon City", _("Quezon City")),
        ("San Juan City", _("San Juan")),
        ("Taguig City", _("Taguig")),
        ("Valenzuela City", _("Valenzuela")),
    ]

    PROVINCES = [
        ("Metro Manila", _("Metro Manila")),
    ]

    user = models.ForeignKey(User, related_name='user_address', on_delete=models.CASCADE, null=True, blank=True)
    line1 = models.CharField(_("address line1"), null=True, blank=False, max_length=155)
    line2 = models.CharField(_("address line2"), null=True, blank=True, max_length=155)
    city = models.CharField(_("address city"), null=True, blank=True, max_length=155)
    province = models.CharField(_("address province"), null=True, blank=True, max_length=155)
    postal_code = models.CharField(_("address postal code"), null=True, max_length=4, blank=False, validators=[only_int])
    default = models.BooleanField(_('default address'), null=True, default=False)

    def __str__(self):
        return f"{self.line1}, {self.line2}, {self.city}, {self.province}, Philippines, {self.postal_code}"

    def display_address(self):
        if self.city:
            if self.city[-1] == "y":
                return f"{self.city}"
            else:
                return f"{self.city} City"
        # if self.line2 and self.city:
        #     return f"{self.line2}, {self.city}"
        # elif self.line1 and self.city:
        #     return f"{self.line1}, {self.city}"

# Social Media Links
class SocialMediaLink(BaseAccountsModel):
    user = models.OneToOneField(User, related_name='user_links', on_delete=models.CASCADE, null=True, blank=True)
    instagram = models.CharField(_("instagram link"), null=True, blank=True, default="", max_length=255)
    facebook = models.CharField(_("facebook link"), null=True, blank=True, default="", max_length=255)
    twitter = models.CharField(_("twitter link"), null=True, blank=True, default="", max_length=255)

    def __str__(self):
        accounts = []
        if self.instagram: accounts.append('Instagram')
        if self.facebook: accounts.append('Facebook')
        if self.twitter: accounts.append('Twitter')
        if len(accounts) == 0:
            return "No social media accounts"
        return f"Linked social media accounts: {', '.join(accounts)}"

# Bank Account Information
class BankAccount(BaseAccountsModel):
    BANKS = [
        ('', 'Choose bank / e-wallet'),
        ("DC/CC", _("Debit/Credit Card")),
        # Direct Debit
        ("BA_BPI", _("Bank of the Philippine Islands (BPI)")),
        ("BA_BDO", _("Banco de Oro (BDO)")),
        ("BA_UBP", _("Unionbank Philippines (UBP)")),
        # E-Wallet
        ("PH_GCASH", _("GCash PH")),
        ("PH_PAYMAYA", _("PayMaya PH")),
        ("PH_GRABPAY", _("GrabPay")),
    ]
    
    user = models.ForeignKey(User, related_name='user_account', on_delete=models.SET_NULL, null=True)
    bank_name = models.CharField(_("bank name"), choices=BANKS, null=True, max_length=55)
    cardholder_name = models.CharField(_("cardholder name"), null=True, max_length=155)
    account_number = models.CharField(_("account number"), null=True, max_length=55)
    exp_date = models.CharField(_("expiration date"), null=True, blank=True, max_length=5, validators=[exp_date])
    cvv = models.CharField(_("card verification value"), null=True, blank=True, max_length=3)
    saved = models.BooleanField(_('saved bank account'), null=True, default=False)
    linked_account_token_id = models.CharField(_("xendit linked account token id"), null=True, blank=True, max_length=155)

    @property
    def get_last_four(self):
        account_number = ''.join(self.account_number.split(' '))
        last_four = account_number[-4:]
        return f"{last_four}"

    def __str__(self):
        if hasattr(self.user, 'shop_info'):
            shop_info = self.user.shop_info
            return f"[{shop_info.shop_name}] {self.cardholder_name} - {self.account_number}"
        else:
            return f"{self.cardholder_name} - {self.account_number}"

class CustomerNotification(BaseAccountsModel):
    user = models.ForeignKey(User, related_name='customer_notifications', on_delete=models.CASCADE, null=True, blank=True)
    sms = models.BooleanField(_('sms notifications'), null=True, default=False)
    email = models.BooleanField(_('email notifications'), null=True, default=False)
    default = models.BooleanField(_('default notifications setting'), null=True, default=False)

    def __str__(self):
        return f"SMS: {self.sms} | Email: {self.email}"

class MerchantNotification(BaseAccountsModel):
    user = models.OneToOneField(User, related_name='merchant_notifications', on_delete=models.CASCADE, null=True)
    # Get an email notification every time we send your revenue to your bank account.
    received_payouts = models.BooleanField(null=True, default=True)

    # Get an email that outlines your orders for the day.
    daily_order_summary = models.BooleanField(null=True, default=True)

templates/accounts/shop-information.html
{% extends 'quicklink/signups.html' %}
{% load static %}

{% block pagetitle %}Merchant Shop Information{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />

    <!-- IntlTelInput Stylesheets -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/css/intlTelInput.css" integrity="sha512-gxWow8Mo6q6pLa1XH/CcH8JyiSDEtiwJV78E+D+QP0EVasFs8wKXq16G8CLD4CJ2SnonHr4Lm/yY2fSI2+cbmw==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/css/intlTelInput.min.css" integrity="sha512-yye/u0ehQsrVrfSd6biT17t39Rg9kNc+vENcCXZuMz2a+LWFGvXUnYuWUW6pbfYj1jcBb/C39UZw2ciQvwDDvg==" crossorigin="anonymous" />
    <style>
        .iti {
            margin: 0.5rem 0;
        }

        .iti__flag {background-image: url("https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/img/flags.png");}

        @media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
        .iti__flag {background-image: url("https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/img/flags@2x.png");}
        }
    </style>
{% endblock %}

{% block scriptsHead %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/imask/6.0.7/imask.min.js" integrity="sha512-qCt/OTd55ilhuXLRNAp/G8uONXUrpFoDWsXDtyjV4wMbvh46dOEjvHZyWkvnffc6I2g/WHSKsaFUCm0RISxnzQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/intlTelInput.min.js" integrity="sha512-OnkjbJ4TwPpgSmjXACCb5J4cJwi880VRe+vWpPDlr8M38/L3slN5uUAeOeWU2jN+4vN0gImCXFGdJmc0wO4Mig==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/utils.js" integrity="sha512-bUcJxlqkiGA3cmoYPuZaLRsyc5ChG9APG4ajom2AXKSlBtOmx4kLV3c8uv/6uSz43FMjI4Q2QI21+D223rT76w==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/utils.min.js" integrity="sha512-JtpGKUjQUqCJmgw3TOr8bkL8QqB8oCbofRU39xgDnRYTfIDvfg0gQs2efeKxBCdwSAP/h3CSqhn87+giWSsxjw==" crossorigin="anonymous"></script>
{% endblock %}

{% block cardContent %}    
        <div class="registration-header">
            {% if not is_edit %}
                <div class="pagination">
                    <a href="{% url 'accounts:merchant-add-shop' %}" class="pagination__circle pagination__circle--active body-big bold">1</a>
                        <div class="pagination__line"></div>
                    <a href="{% url 'accounts:merchant-add-logo' %}" class="pagination__circle body-big bold">2</a>
                        <div class="pagination__line"></div>
                    <a href="{% url 'accounts:merchant-add-settings' %}" class="pagination__circle  body-big bold">3</a>
                        <div class="pagination__line"></div>
                    <a href="{% url 'accounts:merchant-add-delivery' %}" class="pagination__circle body-big bold">4</a>
                        <div class="pagination__line"></div>
                    <a href="{% url 'accounts:merchant-add-payment' %}" class="pagination__circle body-big bold">5</a>
                </div>
            {% endif %}
            <h1 class="bold" style="color: var(--primary-main);">Shop Information</h1>
            <h2 class="body" style="color: var(--muted-default); padding: 0.25rem 0;">Help us get to know your shop better.</h2>
            <p class="caption regular" style="color: var(--muted-lighter);">Note: Your shop information will be publicly visible.</p>
        </div>
        
        <form action="" method="post" style="width: 100%;" id="js-shop-form" autocomplete="off">
            {% csrf_token %}
            <div class="registration-content">
                <p class="subtitle bold">Shop Name<span style="color: var(--failure-main)">*</span></p>
                {{form.shop_name}}
            </div>
            
            <div class="registration-content">
                <p class="subtitle bold">Shop Quicklink Username<span style="color: var(--failure-main)">*</span></p>
                {{form.shop_username}}
                <div class="input__helper__row">
                    <img 
                        src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Account_Creation/icons/fi_info_DX4GENMoh.svg" 
                        alt="Guide" class="registration-content--email-icon" style="width: 1rem; height: 1rem;"
                    >
                    <p class="input__helper caption">This will be used for your order form link (quicklink.ph/username).</p>
                </div>
            </div>

            <div class="registration-content">
                <p class="subtitle bold">Contact Number<span class="subtitle" style="color: var(--muted-lighter)"> (Optional)</span></p>
                {{form.shop_contact_number}}
            </div>

            <div class="registration-content">
                <p class="subtitle bold">Email Address<span class="subtitle" style="color: var(--muted-lighter)"> (Optional)</span></p>
                {{form.shop_email}}
                <!-- <div class="input__helper__row">
                    <img 
                        src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Account_Creation/icons/fi_info_DX4GENMoh.svg" 
                        alt="Guide" class="registration-content--email-icon" style="width: 1rem; height: 1rem;"
                    >
                    <p class="input__helper caption">Your customers will contact you through this email address.</p>
                </div> -->
            </div>
            

            <div class="registration-content">
                <p class="subtitle bold">Shop Address<span class="subtitle" style="color: var(--muted-lighter)"> (Optional)</span></p>
                {{form.line1}}
                {{form.line2}}
                {{form.city}}
                <div class="registration-content registration-content__row">
                    <div class="registration-content__input--small" style="padding-right: 4px;">
                        {{form.province}}
                        <!-- <select name="city" class="wide input default subtitle" id="id_city" data-cities-url="{% url 'accounts:load-cities' %}">
                            {% for city in cities %}
                                {% if city.name|title == selected_city %}
                                    <option value="{{ city.name|title }}" selected>{{ city.name|title }}</option>
                                {% else %}
                                    <option value="{{ city.name|title }}">{{ city.name|title }}</option>
                                {% endif %}
                            {% endfor %}
                        </select> -->
                    </div>
                    <div class="registration-content__input--small" style="padding-left: 4px;">{{form.postal_code}}</div>
                </div>
            </div>

            <!-- <div class="registration-content">
                <p class="subtitle bold">Social Media Links</p>
                {{form.instagram}}
                {{form.facebook}}
                {{form.twitter}}
            </div> -->

            <!-- To edit style, edit .errorlist (ul) and .errorlist li (each message) -->
            <div id="form-errors">{{ form.errors.as_json }}</div>

            <div class="registration-content">
                <button type="submit" name="next" style="margin: 1rem 0; width: 100%;" class="primary-btn subtitle" id="js-shop-info-submit">{% if is_edit %}Save{% else %}Next{% endif %}</button>
                {% if is_edit %}
                    <a href="{% url 'accounts:shop' %}" class="btn__back" style="margin: 0;">
                        <button type="button" class="secondary-btn subtitle" style="width: 100%;">
                            {% if is_edit %}Cancel{% else %}Back{% endif %}
                        </button>
                    </a>
                {% endif %}
            </div>
        </form>
{% endblock %}

{% block scriptsBody %}
    <!-- Mixpanel  -->
    <script>
        const userId = $("#js-user-uuid").text();
        mixpanel.identify(`QL_merchant_dev_${userId}`);
        const distinctId = mixpanel.get_distinct_id();
        
        const submitBtn = $("#js-shop-info-submit");

        submitBtn.click(function() {
            mixpanel.register({
                'Shop Name': `${$("#id_shop_name").val()}`,
                'Contact Number': `${$("#id_shop_contact_number").val()}`,
                'Display Email': `${$("#id_shop_email").val()}`,
                'Username': `${$("#id_shop_username").val()}`,
                'Address': `${$("#id_city").val()}`,
                'Instagram': `${$("#id_instagram").val()}`,
                'Facebook': `${$("#id_facebook").val()}`,
                'Twitter': `${$("#id_twitter").val()}`
            });
        });

        mixpanel.track_forms('#js-shop-form', 'Registered Shop Information', {
            'Shop Name': `${$("#id_shop_name").val()}`,
            'Contact Number': `${$("#id_shop_contact_number").val()}`,
            'Display Email': `${$("#id_shop_email").val()}`,
            'Username': `${$("#id_shop_username").val()}`,
            'Address': `${$("#id_city").val()}`,
            'Instagram': `${$("#id_instagram").val()}`,
            'Facebook': `${$("#id_facebook").val()}`,
            'Twitter': `${$("#id_twitter").val()}`
        });
    </script>

    <!-- Load Cities -->
    <script>
        $("#id_province").change(function() {
            var url = $("#id_city").attr("data-cities-url");
            var provinceId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'province_pk': provinceId
                },
                success: function(data) {
                    $("#id_city").html(data);
                    $('#id_city').niceSelect('update');
                }
            });
        });
    </script>

    <!-- iMask Lightweight JS Plugin -->
    <script>
        var contactNumberInput = document.getElementById('id_shop_contact_number');
        var maskOptions = {
            mask: '000 000 0000'
        };
        var mask = IMask(contactNumberInput, maskOptions);
    </script>

    <!-- intlTelInput Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/intlTelInput.js" integrity="sha512-lib7WdJvAnfLLBi5AHdN+wUkcWwpu1fmYzyEHQijZq7WedcwBiwdVNbcML2rAtKvwtOIU7thMGB+O9Kpb9g2Cw==" crossorigin="anonymous"></script>
    <script>
        var contactNumberInput = document.querySelector("#id_shop_contact_number");

        // To edit the style of intlTelInput, edit .iti {}
        // Check the documentation for more info: https://github.com/jackocnr/intl-tel-input

        var iti = intlTelInput(contactNumberInput, {
            utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.12/js/utils.js",
            initialCountry: "PH",
            separateDialCode: true,
        })
    </script>

    <!-- Nice Select lightweight JQuery plugin -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js" integrity="sha512-NqYds8su6jivy1/WLoW8x1tZMRD7/1ZfhWG/jcRQLOzV1k1rIODCpMgoBnar5QXshKJGV7vi0LXLNXPoFsM5Zg==" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('#id_city').niceSelect();
            $('#id_province').niceSelect();
        });
    </script>

    <!-- NOTY Notifications -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js" integrity="sha512-lOrm9FgT1LKOJRUXF3tp6QaMorJftUjowOWiDcG5GFZ/q7ukof19V0HKx/GWzXCdt9zYju3/KhBNdCLzK8b90Q==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.js" integrity="sha512-mgZL3SZ/vIooDg2mU2amX6NysMlthFl/jDbscSRgF/k3zmICLe6muAs7YbITZ+61FeUoo1plofYAocoR5Sa1rQ==" crossorigin="anonymous"></script>

    <!-- NOTY -->
    <script>
        var errors = $('#form-errors').text();
        var jsonErrors = JSON.parse(errors);

        var errorMessages = [];

        for (var k in jsonErrors) {
            for (var i in Object.keys(jsonErrors[k])) {
                errorMessages.push([jsonErrors[k][i]['message']]);
            }
        }

        for (i = 0; i <= Object.keys(errorMessages).length; i++) {
            if (errorMessages[String(i)] != undefined) {
                new Noty({
                    type: 'error',
                    theme: 'bootstrap-v4',
                    text: errorMessages[String(i)],
                    layout: "topRight",
                    timeout: 5000,
                    progressBar: true,
                }).show();
            }
        }
    </script>
{% endblock %}