apps/customers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.marketplace, name='marketplace'),
    path('shop/<str:username>/', views.view_products, name='view-products'),
    path('shop/<str:username>/<str:product_pk>/', views.add_order, name='add-order'),
    path('shop/<str:username>/<str:item_pk>/edit/', views.edit_order, name='edit-order'),
    path('update-cart-item/', views.update_item, name='update-item'),
    path('checkout/<str:order_id>/', views.checkout, name='checkout'),
    path('checkout/<str:order_id>/payment/<str:slug>/', views.payment, name='payment'),
    path('checkout/<str:order_id>/payment/bank/failed-linking/', views.failed_bank_linking, name='failed-bank-linking'),
    path('checkout/<str:order_id>/payment/bank/account-linking/', views.bank_account_linking, name='bank-account-linking'),
    path('checkout/<str:order_id>/payment/bank/pay/', views.bank_transfer_payment, name='bank-payment'),
    path('checkout/<str:order_id>/payment/bank/pay/otp/', views.bank_transfer_otp, name='payment-otp'),
    path('checkout/complete/<str:order_id>/', views.order_completion, name='order-completion'),
    path('checkout/invoice/<str:order_id>/', views.order_invoice, name='order-invoice'),
    path('register/', views.account_creation, name='register'),
    path('login/', views.customer_login, name='login'),
    path('logout/', views.customer_logout, name='logout'),
    path('register/verification/<str:user_id>/', views.email_verification, name='email-verification'),
    path('register/confirmation/<uidb64>/<token>/', views.email_confirmation, name='email-confirmation'),
    path('register/information/', views.register_customer_information, name='register-information'),
    path('register/address/', views.register_customer_address, name='register-address'),
    path('register/payment/', views.register_customer_payment, name='register-payment'),
    path('register/payment/<str:slug>/', views.register_customer_payment_method, name='register-payment-method'),
    path('register/notifications/', views.register_customer_notifications, name='register-notifications'),
    path('register/complete/', views.register_complete, name='register-complete'),
    path('orders/', views.account_orders, name='orders'),
    path('reorder/<str:order_id>/', views.reorder, name='reorder'),
    path('load_cities/', views.load_cities, name='load-cities'),
    path('ewallet-callback/', views.ewallet_callback, name='ewallet-callback')
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.LOCAL_DEV:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

handler400 = 'accounts.views.handler_400'
handler403 = 'accounts.views.handler_403'
handler404 = 'accounts.views.handler_404'
handler500 = 'accounts.views.handler_500'

apps/finances/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('revenues/', views.revenues, name='revenues'),
]

apps/orders/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.orders, name='order-summary'),
    # path('delete-order/<str:order_pk>/', views.delete_order, name='delete-order'),
    path('pending/', views.pending_orders, name='pending-orders'),
    path('status-change/', views.order_status_change, name='order-status-change'),
    # path('update-change/', views.send_update_change, name="send-update-change")
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.products, name='products'),
    path('add/', views.add_product, name='add-product'),
    path('set-active/', views.set_products_as_active, name='set-product-active'),
    path('set-inactive/', views.set_products_as_inactive, name='set-products-inactive'),
    path('delete-selected/', views.delete_selected_products, name='delete-selected-products'),
    # path('product/<str:product_pk>/', views.product_details, name='product'),
    path('update/<str:product_pk>/', views.update_product, name='update-product'),
    path('duplicate/<str:product_pk>/', views.duplicate_product, name='duplicate-product'),
    path('delete/<str:product_pk>/', views.delete_product, name='delete-product')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
import accounts

# import debug_toolbar

urlpatterns = [
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    path('_nested_admin/', include('nested_admin.urls')),
    # url(r'^hijack/', include('hijack.urls', namespace='hijack')),
    path('accounts/', include('allauth.urls')),
    path('avatar/', include('avatar.urls')),
    path('', include(('accounts.urls', 'accounts'), namespace='users')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('finances/', include(('finances.urls', 'finances'), namespace='finances')),
]

if settings.LOCAL_DEV:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    handler400 = 'accounts.views.handler_400'
    handler403 = 'accounts.views.handler_403'
    handler404 = 'accounts.views.handler_404'
    handler500 = 'accounts.views.handler_500'

apps/customers/models.py
from django.db import models

# Create your models here.

apps/customers/views.py
from math import e
import os
import environ
from django.conf import settings

from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.cache import cache_page
from django.views.decorators.cache import cache_control
from django.utils.translation import ugettext_lazy as _
from django.http import HttpResponse
import django_hosts

from django.contrib.auth.decorators import login_required
from accounts.decorators import allowed_users

from orders.models import Order, OrderItem, OrderInformation
from products.models import *
from accounts.models import *
from orders.forms import *

from .services import *
from .selectors import *

import json
import base64

# Create your views here.
@cache_page(60)
def marketplace(request):
    # all_shops = ShopInformation.objects.all()
    # shops_list = []
    # for shop in all_shops:
    #     products = Product.objects.filter(user=shop.user, active=True)
    #     if products.count() > 0: shops_list.append(shop.user)
    # shops = ShopInformation.objects.filter(user__in=shops_list)
    shops = ShopInformation.objects.filter(user__role="MERCHANT", user__shop_product__isnull=False).distinct().order_by("shop_name")
    context = {'shops':shops, 'marketplace':True}
    return render(request, 'quicklink/marketplace.html', context)

# View Products (Customers)
@cache_page(5)
@cache_control(private=True)
def view_products(request, username):
    shop = ShopInformation.objects.get(shop_username=username) # Get Shop Information
    shop_owner = shop.user # Get Shop User Profile
    products = Product.objects.filter(user=shop_owner, active=True).order_by("name") # Get Active Shop Products
    address = Address.objects.get(user=shop_owner, default=True) # Get Shop Settings
    customer = get_customer(request.user, request.COOKIES, request.session) # Get Customer
    order = get_order(customer, shop_owner) # Get or Create Current Order
    items = order.orderitem_set.all().order_by("id") # Get items under that order
    editable_cart = True # Cart is Editable
    context = {'products':products, 'shop':shop, 'items':items, 'order':order, 'address':address, 'editable_cart':editable_cart}
    return render(request, 'shops/products.html', context)

# Add Products to Cart (Customers)
@csrf_exempt
@cache_page(10)
@cache_control(private=True)
def add_order(request, username, product_pk):
    shop = ShopInformation.objects.get(shop_username=username) # Get Shop Information
    shop_owner = shop.user # Get Shop User Profile
    products = Product.objects.filter(user=shop_owner, active=True).order_by("name") # Get Active Shop Products
    editable_cart = True # Cart is Editable

    product = Product.objects.get(id=product_pk) # Get product according to url pk
    images = product.get_images # Get product images, see models for function
    sizes = product.get_sizes # Get product sizes, see models for function
    addons = product.get_addons # Get product addons, see models for function
    
    customer = get_customer(request.user, request.COOKIES, request.session) # Get Customer (function)
    order = get_order(customer, shop_owner) # Get Current Order
    items = order.orderitem_set.all().order_by("id") # Get items under that order
    
    if product.made_to_order: product_stock = None
    else: product_stock = product.stock
    form = OrderForm(request.POST or None, product_stock=product_stock)
    if request.method == 'POST':       
        # Save form if form is valid
        if form.is_valid():
            order_item = add_to_cart(shop, order, product, request.POST, form.cleaned_data) # Add to cart function
            messages.success(request, f'Successfully added {order_item.quantity} {order_item.product.name} to cart!')
        else:
            messages.error(request, f'An error occurred while adding a product to cart. Please try again later!')
        return redirect(django_hosts.resolvers.reverse('view-products', args=(shop.shop_username, ), host='shops'))

    context = {
        'shop':shop, 
        'products':products,
        'items':items,
        'order':order,
        'editable_cart':editable_cart,
        'form':form,
        'product':product,
        'images':images,
        'sizes':sizes, 
        'addons':addons
    }
    return render(request, 'shops/order_form.html', context)

# Edit Products in Cart (Customers)
@csrf_exempt
@cache_page(10)
@cache_control(private=True)
def edit_order(request, username, item_pk):
    shop = ShopInformation.objects.get(shop_username=username) # Get Shop Information
    shop_owner = shop.user # Get Shop User Profile
    products = Product.objects.filter(user=shop_owner, active=True) # Get Active Shop Products
    editable_cart = True # Cart is Editable
    product_order = OrderItem.objects.get(id=item_pk) # Get order item according to url pk
    product = product_order.product # Get product according to order item 
    images = product.get_images # Get product images, see models for function
    sizes = product.get_sizes # Get product sizes, see models for function
    addons = product.get_addons # Get product addons, see models for function
    size = product_order.size # Get selected size
    addon = product_order.addons # Get selected addons
    customer = get_customer(request.user, request.COOKIES, request.session) # Get Customer
    order = get_order(customer, shop_owner) # Get or Create Current Order
    items = order.orderitem_set.all().order_by("id") # Get items under that order

    if product.made_to_order: product_stock = None
    else: product_stock = product.stock
    form = OrderForm(request.POST or None, instance=product_order, product_stock=product_stock)

    if request.method == 'POST':
        # Save form if form is valid
        if form.is_valid():
            edit_cart_item(shop, order, product_order, request.POST, form.cleaned_data)
            messages.success(request, f'Successfully edited cart item!')
        else:
            messages.error(request, f'An error occurred while editing a cart item. Please try again later!')
        return redirect(django_hosts.resolvers.reverse('view-products', args=(shop.shop_username, ), host='shops'))

    context = {
        'shop':shop, 
        'products':products,
        'items':items,
        'order':order,
        'editable_cart':editable_cart,
        'form':form,
        'product':product,
        'images':images,
        'sizes':sizes,
        'selected_size':size, 
        'addons':addons,
        'selected_addon':addon
    }
    return render(request, 'shops/edit_order.html', context)

from ph_geography.models import Province, Municipality
def load_cities(request):
    province = request.GET.get('province_pk')
    province = Province.objects.get(name=province.upper())
    # municipalities = Province.objects.select_related("municipality").get(name=province.upper())
    municipalities = Municipality.objects.filter(province=province).order_by('name')
    return render(request, 'dropdowns/cities.html', {'municipalities':municipalities})

from discord_webhook import DiscordWebhook, DiscordEmbed

def ewallet_callback(request):
    user = request.user
    icon_url = "https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Marketplace/Settings/Group_358_s1885d_rX-X.png"

    print(request.GET)

    event = request.GET.get('event') # Identifies the event triggering a notification to merchant. ewallet.capture occurs when eWallet issuer confirms the payment status of a transaction
    business_id = request.GET.get('business_id') # Merchant Business ID.
    created = request.GET.get('created') # ISO 8601 Timestamp for callback notification creation. Timezone UTC+0.
    time_created = datetime.datetime.strptime(created, "%c")
    data = request.GET.get('data') # eWallets charge object will be nested in this parameter. See here for full definitions.
    payment_status = data.status # Status of charge request - SUCCEEDED, PENDING, FAILED, VOIDED
    currency = data.currency
    charge_amount = data.charge_amount # Requested charge amount from merchant
    capture_amount = data.capture_amount # Requested capture amount from merchant. In requests where checkout_method = ONE_TIME_PAYMENT, capture_amount will always be the same as charge_amount
    channel_code = data.channel_code # Channel Code specifies which eWallet will be used to process the transaction - PH_PAYMAYA, PH_GCASH, PH_GRABPAY

    if settings.LOCAL_DEV == False and user.is_authenticated:
        if hasattr(user, 'shop_info'):
            if hasattr(user.shop_info, "shop_logo"):
                icon_url = user.shop_info.shop_logo.logo.url
        else:
            if hasattr(user, 'customer_info'):
                if hasattr(user.customer_info, "customer_dp"):
                    icon_url = user.customer_info.customer_dp.profile_pic.url

    if request.method == 'POST':
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        summary = request.POST.get('summary', '')
        description = request.POST.get('description', '')

        discord_url = "https://discord.com/api/webhooks/863015986626166815/wFaRNNHI9hWK7inujBOEMnc-ZS-BYidORpoCI6kJJJeB63NK9-KQLMqCx5C3ReDLdQhF"
        webhook = DiscordWebhook(url=discord_url)
        embed = DiscordEmbed(
            title="New eWallet Payment!", description="MONEEEEEH", color='f8f8f8'
        )
        try:
            embed.set_author(
                name=name,
                icon_url=icon_url,
            )
        except:
            embed.set_author(
                name=name
            )
        embed.add_embed_field(name="Event", value=f"{event} (Business ID: {business_id})", inline=False)
        embed.add_embed_field(name="Channel", value=f"{channel_code}", inline=False)
        embed.add_embed_field(name="Payment Status", value=f"{payment_status}", inline=False)

templates/quicklink/coming-soon.html
<div class="status-container">
    <div class="coming__soon">
        <p class="overline bold coming__soon">Coming Soon</p>
    </div>
</div>

templates/quicklink/dashboard.html
{% extends 'quicklink/app.html' %}
{% load static %}
{% load humanize %}
{% load growth_rate %}

{% block pagetitle %}Dashboard{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{% endblock %}

{% block maincontent %}
<div class="dashboard__container">
    <div class="dashboard__wrapper">
        <div class="dashboard__header__wrapper">
            <div class="dashboard__header__content">
                <h1 class="body-big extra-bold">Hey there!</h1>
            </div>
        </div>
    </div>
    {% if not products %}
        <div class="dashboard__no-products">
            <div class="dashboard__no-products__card">
                <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Dashboard/illustrations/placeholder-2x_eZhpLuaqx.png" alt="" class="dashboard__no-products__img">
                <h2 class="dashboard__no-products__text bold">Oh! You haven’t added any product for sale yet!</h2>
                <a href="{% url 'products:add-product' %}">
                    <button class="primary-btn subtitle bold">
                        Add Product
                        <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Design_System/Icons/Buttons/add_product_icon_YYLwT5YiFK1.png" alt="" class="primary-btn-icon">
                    </button>
                </a>
            </div>
        </div>
    {% endif %}
    <div class="dashboard__wrapper">
        <div class="dashboard__cards">
            <div class="dashboard__card">
                <div class="dashboard__card__content">
                    <h3 class="dashboard__card__content__title bold">Total Revenue</h3>
                    <p class="dashboard__card__content__total header bold">PHP {{ total_revenues|intcomma }}</p>
                    <div class="dashboard__card__content__row">
                        <img src="
                            {% if revenue_growth_rate > 0 %}
                                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Dashboard/increase_chevron_IbclpV7P3w.png
                            {% elif revenue_growth_rate == 0 %}
                                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Dashboard/default_chevron_VV-7T5jHJEm.png
                            {% else %}
                                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Dashboard/decrease_chevron_quvqEwaqZ.png
                            {% endif %}" 
                        alt="">
                        <p class="subtitle dashboard__rate {% if revenue_growth_rate > 0 %}positive{% elif revenue_growth_rate < 0 %}negative{% endif %}">{{ revenue_growth_rate|growth_rate }}<span class="subtitle">since last month</span></p>
                    </div>
                </div>
                <div class="dashboard__card__summary">
                    <a href="{% url 'finances:revenues' %}" class="dashboard__card__content__row">
                        <button class="tertiary-btn subtitle bold">View full summary</button>
                        <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Design_System/Icons/Buttons/tertiary_icon-enabled-hover-pressed_6lPUe6B7S36.svg" alt="">
                    </a>
                </div>
            </div>
            <div class="dashboard__card">
                <div class="dashboard__card__content">
                    <h3 class="dashboard__card__content__title bold">Orders</h3>
                    <p class="dashboard__card__content__total header bold">{% if orders %}{{ orders.count }}{% else %}0{% endif %}</p>
                    <div class="dashboard__card__content__row">
                        <img src="
                            {% if order_growth_rate > 0 %}
                                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Dashboard/increase_chevron_IbclpV7P3w.png
                            {% elif order_growth_rate == 0 %}
                                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Dashboard/default_chevron_VV-7T5jHJEm.png
                            {% else %}
                                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Dashboard/decrease_chevron_quvqEwaqZ.png
                            {% endif %}" 
                        alt="">
                        <p class="subtitle dashboard__rate {% if order_growth_rate > 0 %}positive{% elif order_growth_rate < 0 %}negative{% endif %}">{{ order_growth_rate|growth_rate }}<span class="subtitle">since last month</span></p>
                    </div>
                </div>
                <div class="dashboard__card__summary">
                    <a href="{% url 'orders:order-summary' %}" class="dashboard__card__content__row">
                        <button class="tertiary-btn subtitle bold">View all orders</button>
                        <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Design_System/Icons/Buttons/tertiary_icon-enabled-hover-pressed_6lPUe6B7S36.svg" alt="">
                    </a>
                </div>
            </div>
            <div class="dashboard__card" style="opacity: 0;">
                <div class="dashboard__card__content">
                    <h3 class="dashboard__card__content__title bold">Order Form Clicks</h3>
                    <p class="dashboard__card__content__total disabled header bold">0</p>
                    <div class="dashboard__card__content__row">
                        <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Dashboard/default_chevron_VV-7T5jHJEm.png" alt="">
                        <p class="subtitle">Coming Soon</p>
                    </div>
                </div>
                <div class="dashboard__card__summary">
                    <div class="dashboard__card__content__row">
                        <button class="tertiary-btn disabled subtitle bold"></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="dashboard__cards">
            <div class="dashboard__card whole">
                <div class="dashboard__card__content">
                    <div class="dashboard__card__title">
                        <h3 class="dashboard__card__content__title bold">Pending Items</h3>
                        <div class="dashboard__card__filter">
                            <button type="button" class="primary-btn subtitle bold js_buttons" id="id_today" data-items-url="{% url 'accounts:load-items' %}">Today</button>
                            <button type="button" class="tertiary-btn subtitle bold js_buttons" id="id_tomorrow">Tomorrow</button>
                            <button type="button" class="tertiary-btn subtitle bold js_buttons" id="id_this_week">This Week</button>
                        </div>
                    </div>
                </div>
                <div class="dashboard__card__items" id="id_pending_items">
                    {% if pending_items %}
                        {% for item, value in pending_items.items %}
                            <div class="dashboard__card__item">
                                <p class="regular dashboard__card__item__name">{{ item }}</p>
                                <p class="extra-bold dashboard__card__item__quantity">{{ value }}</p>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="dashboard__card__no__items">
                            <p class="subheader bold" style="color: var(--primary-alt);">No pending items for today!</p>
                        </div>
                    {% endif %}
                </div>
                <div class="dashboard__card__summary pending__items">
                    <a href="{% url 'orders:pending-orders' %}" class="dashboard__card__content__row">
                        <button class="tertiary-btn subtitle bold">View all pending orders</button>
                        <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Design_System/Icons/Buttons/tertiary_icon-enabled-hover-pressed_6lPUe6B7S36.svg" alt="">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scriptsBody %}
    <!-- Mixpanel -->
    <script>
        mixpanel.track('Dashboard Visited', {'Shop Name': `${shopName}`});
    </script>

    <!-- Pending Items -->
    <script>
        var today = $("#id_today");
        var tomorrow = $("#id_tomorrow");
        var thisWeek = $("#id_this_week");
        var pendingItems = $("#id_pending_items");
        var allBtns = $(".js_buttons");

        // JavaScript function to AJAX call into load_items url and get items data.
        function loadItems(days) {
            var url = today.attr("data-items-url");
            $.ajax({
                url: url,
                data: {
                    'days': days
                },
                success: function(data) {
                    pendingItems.html(data);
                },
                error: function(err) {
                    console.log(err)
                }
            });
        }

        function changeBtns(button) {
            allBtns.each(function() {
                $(this).removeClass("primary-btn");
                $(this).addClass("tertiary-btn");
            })

            button.removeClass("tertiary-btn");
            button.addClass("primary-btn");
        }

        // Click on tomorrow, load into function with timedelta 0 day/s
        $(today.click(function() {
            loadItems(0);
            changeBtns($(this));
        }));
        
        // Click on tomorrow, load into function with timedelta 1 day/s
        $(tomorrow.click(function() {
            loadItems(1);
            changeBtns($(this));
        }));

        // Click on tomorrow, load into function with timedelta 1 day/s
        $(thisWeek.click(function() {
            loadItems(7);
            changeBtns($(this));
        }));
    </script>
{% endblock %}

templates/quicklink/navbar.html
{% load static %}
{% load active_link_tags %}
    
<nav class="sidebar">
    <div class="sidebar__ql-logo">
        <img 
            src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/logos/white/white-logo-1x_hVgWTlNgE.png" 
            alt="Quicklink Logo" 
            srcset="
                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/logos/white/white-logo-4x_WteqAOm6dc7.png 4x,
                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/logos/white/white-logo-3x_tQQd4iCYJB.png 3x,
                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/logos/white/white-logo-2x_tMFeicZb8.png 2x,
                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/logos/white/white-logo-1x_hVgWTlNgE.png 1x,"
        >
    </div>
    <div class="sidebar__menu">
        <ul class="sidebar__items">
            <!-- 1st nav button -->
            <a href="{% url 'accounts:dashboard' %}" class="nav__link body bold {% active_link 'accounts:dashboard' strict=True %}">
                <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Navbar/white-dashboard-icon_xuNVZx7vkS.svg" 
                alt="Dashboard Icon" id="navbar__icons">
                Dashboard
            </a>
            <!-- 2nd nav button and sub bar -->
            <div class="nav__link body bold" id="js-feat-btn">
                <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Navbar/white-shop-icon_Xxd8mPFmt-b.svg"
                alt="Shop Icon" id="navbar__icons">
                Shop
                <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Navbar/white-chevron-right_hCqRvYLHA.svg" class="nav__chevron rotate" id="js-first-nav-link">
            </div>
            <ul class="sidebar__items-subitems show" id="js-feat-show">
                <a href="{% url 'accounts:shop' %}" class="sidebar_sub-item subtitle semi-bold {% active_link 'accounts:shop' strict=True %}" id="sidebar__subitem-custom">My Shop</a>
                <a href="{% url 'orders:order-summary' %}" class="sidebar_sub-item subtitle semi-bold {% active_link 'orders:order-summary' strict=True %}" id="sidebar__subitem-custom">All Orders</a>
                <a href="{% url 'orders:pending-orders' %}" class="sidebar_sub-item subtitle semi-bold {% active_link 'orders:pending-orders' strict=True %}" id="sidebar__subitem-custom">Pending Items</a>
                <a href="{% url 'products:products' %}" class="sidebar_sub-item subtitle semi-bold {% active_link 'products:products' strict=True %}" id="sidebar__subitem-custom">Products</a>
            </ul>
            <!--3rd nav button and sub bar -->
            <div class="nav__link body bold" id="js-serv-btn">
                <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Navbar/white-finances-icon_naPJo2Dej.svg"
                alt="Shop Icon" id="navbar__icons">
                Finances
                <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Navbar/white-chevron-right_hCqRvYLHA.svg" class="nav__chevron rotate" id="js-second-nav-link">
            </div>
            <ul class="sidebar__items-subitems show" id="js-serv-show">
                <a href="{% url 'finances:revenues' %}" class="sidebar_sub-item subtitle semi-bold {% active_link 'finances:revenues' strict=True %}" id="sidebar__subitem-custom">Total Revenue</a>
            </ul>
            <!-- 4th nav button and sub bar -->
            <div class="nav__link body bold" id="js-cldk-btn">
                <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Navbar/white-settings-icon_WJexo4RiDrW.svg"
                alt="Shop Icon" id="navbar__icons">
                Settings
                <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Navbar/white-chevron-right_hCqRvYLHA.svg" class="nav__chevron rotate" id="js-third-nav-link">
            </div>
            <ul class="sidebar__items-subitems show" id="js-cldk-show">
                <a href="{% url 'accounts:account-settings' %}" class="sidebar_sub-item subtitle semi-bold {% active_link 'accounts:account-settings' strict=True %}" id="sidebar__subitem-custom">Account</a>
                <!-- <a href="{% url 'accounts:notification-settings' %}" class="sidebar_sub-item subtitle semi-bold {% active_link 'accounts:notification-settings' strict=True %}" id="sidebar__subitem-custom">Notifications</a>
                <a href="{% url 'accounts:resource-settings-faqs' %}" class="sidebar_sub-item subtitle semi-bold {% active_link 'accounts:resource-settings-faqs' %}" id="sidebar__subitem-custom">Resources</a> -->
            </ul>
        </ul>
    </div>
</nav>
  
<nav class="mobile__nav">
    <div class="mobile__nav__items">
        
    </div>
</nav>

<script>
    $('#js-feat-btn').click(function(){
        $('#js-feat-show').toggleClass("show");
        $('#js-first-nav-link').toggleClass("rotate");
    });
    
    $('#js-serv-btn').click(function(){
        $('#js-serv-show').toggleClass("show");
        $('#js-second-nav-link').toggleClass("rotate");
    });
    $('#js-cldk-btn').click(function(){
        $('#js-cldk-show').toggleClass("show");
        $('#js-third-nav-link').toggleClass("rotate");
    });
</script>