apps/finances/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('revenues/', views.revenues, name='revenues'),
]

apps/products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.products, name='products'),
    path('add/', views.add_product, name='add-product'),
    path('set-active/', views.set_products_as_active, name='set-product-active'),
    path('set-inactive/', views.set_products_as_inactive, name='set-products-inactive'),
    path('delete-selected/', views.delete_selected_products, name='delete-selected-products'),
    # path('product/<str:product_pk>/', views.product_details, name='product'),
    path('update/<str:product_pk>/', views.update_product, name='update-product'),
    path('duplicate/<str:product_pk>/', views.duplicate_product, name='duplicate-product'),
    path('delete/<str:product_pk>/', views.delete_product, name='delete-product')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
import accounts

# import debug_toolbar

urlpatterns = [
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    path('_nested_admin/', include('nested_admin.urls')),
    # url(r'^hijack/', include('hijack.urls', namespace='hijack')),
    path('accounts/', include('allauth.urls')),
    path('avatar/', include('avatar.urls')),
    path('', include(('accounts.urls', 'accounts'), namespace='users')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('finances/', include(('finances.urls', 'finances'), namespace='finances')),
]

if settings.LOCAL_DEV:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    handler400 = 'accounts.views.handler_400'
    handler403 = 'accounts.views.handler_403'
    handler404 = 'accounts.views.handler_404'
    handler500 = 'accounts.views.handler_500'

apps/finances/models.py
from django.db import models

from accounts.models import User

# Create your models here.
class BaseFinancesModel(models.Model):
    class Meta:
        abstract = True
        app_label = 'finances'

class Summary(BaseFinancesModel):
    shop = models.ForeignKey(User, related_name="shop_summary", on_delete=models.SET_NULL, null=True)
    # Total Expected Revenue
    total_revenue = models.DecimalField(null=True, default=0, max_digits=15, decimal_places=2)

    # Payments Received
    payments_received = models.DecimalField(null=True, default=0, max_digits=15, decimal_places=2)

    # Accounts Receivables
    total_receivables = models.DecimalField(null=True, default=0, max_digits=15, decimal_places=2)

apps/finances/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from accounts.decorators import allowed_users, unauthenticated_merchant
from accounts.models import User, ShopGeneralSettings
from orders.models import Order
from .models import Summary
from decimal import Decimal

# Create your views here.
@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=[User.Types.MERCHANT, User.Types.QUICKIES, User.Types.ADMIN])
def revenues(request):
    shop = request.user
    if hasattr(shop, "shop_info"): settings = ShopGeneralSettings.objects.get(shop=shop.shop_info)
    else: settings = None
    summary, created = Summary.objects.get_or_create(shop=shop)
    orders = Order.objects.filter(shop=shop, complete=True).order_by('order_date')

    # Total Expected Revenue
    total_revenue = Decimal(0)
    for order in orders:
        if order.fees != 0:
            total_revenue += order.subtotal
        else:
            total = order.total - (order.total * Decimal(0.04))
            total_revenue += total
    summary.total_revenue = total_revenue

    # Payments Received
    received_orders = orders.filter(payment_status="RECEIVED")
    payments_received = Decimal(0)
    for order in received_orders:
        if order.fees != 0:
            payments_received += order.subtotal
        else:
            total = order.total - (order.total * Decimal(0.04))
            payments_received += total
    summary.payments_received = payments_received

    # Payments Receivables
    receivables_orders = orders.all().exclude(payment_status="RECEIVED")
    receivables = Decimal(0)
    for order in receivables_orders:
        if order.fees != 0:
            receivables += order.subtotal
        else:
            total = order.total - (order.total * Decimal(0.04))
            receivables += total
    summary.total_receivables = receivables
    summary.save()

    context = {"orders":orders, "settings":settings, "total_revenue":total_revenue, "payments_received":payments_received, "receivables":receivables}
    return render(request, 'finances/revenue.html', context)

templates/finances/revenue-2.html
{% extends 'quicklink/app.html' %}
{% load static %}

{% block pagetitle %}Products{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static '/css/products/products.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.css" integrity="sha512-0p3K0H3S6Q4bEWZ/WmC94Tgit2ular2/n0ESdfEX8l172YyQj8re1Wu9s/HT9T/T2osUw5Gx/6pAZNk3UKbESw==" crossorigin="anonymous">
{% endblock %}

{% block maincontent %}
    <div class="products__container">
        <div class="products__header">
            <div class="products__header__wrapper">
                <div class="products__searchbar">
                    <form action="{% url 'products:products' %}">
                        <input class="searchbar body regular" type="search" placeholder="Search" name="search">
                    </form>
                </div>
                <div class="products__header__btns">
                    <button type="button" class="secondary-btn subtitle bold"
                        id="js-copy-form-link-btn" data-clipboard-text="{{ form_link }}">
                        Copy Form Link
                    </button>

                    <a href="{% url 'products:add-product' %}" style="text-decoration: none;">
                        <button class="primary-btn subtitle bold">
                            Add Product
                            <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Design_System/Icons/Buttons/add_product_icon_YYLwT5YiFK1.png" alt="Add">
                        </button>
                    </a>
                </div>
            </div>
        </div>

        <div class="products__list">
            <div class="products__wrapper">
                <table class="products__table" id="js-products-table">
                    <thead>
                        <tr class="products__table__header hide" id="js-select-products">
                            <th class="product__table__cell" colspan="6">
                                <div class="products__table__btns">
                                    <button type="button" class="selected__products__container" id="js-deselect-all-btn">
                                        <label class="checkbox">
                                            <input type="checkbox" onclick="return false;" checked />
                                            <span class="checkmark checkmark__small"></span>
                                        </label>
                                        <p class="subtitle bold" id="js-selected-input" style="margin-left: 0.5rem;"></p>
                                    </button>
                                    <button type="button" class="secondary-btn subtitle bold set-as-inactive__btn" id="js-set-as-inactive-btn">Set as inactive</button>
                                    <button type="button" class="secondary-btn warning subtitle bold js-open-delete-modal" id="js-open-delete-modal-selected">Delete</button>
                                </div>
                            </th>
                        </tr>
                        <tr class="products__table__header" id="js-normal-table-header">
                            <th class="product__table__cell">
                                <label class="checkbox">
                                    <input type="checkbox" name="select_all" id="js-select-all">
                                    <span class="checkmark checkmark__small"></span>
                                </label>
                            </th>
                            <th class="product__table__cell">
                                <div style="display: flex; justify-content: center; align-items: center; align-content: center;">
                                    <p class="overline bold">Product</p>
                                    <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Orders/fi_chevron-down_V5AWvLbdy.svg" class="sort-chevron" id="js-sort-chevron-1" alt="Sort">
                                </div>
                            </th>
                            <th class="product__table__cell overline bold">Stocks</th>
                            <th class="product__table__cell overline bold">Total Sold</th>
                            <th class="product__table__cell overline bold">Available</th>
                            <th></th>
                        </tr>
                    </thead>
                {% if not products %}
                </table>
                    <div class="table__placeholder__container">
                        <div class="table__placeholder__wrapper">
                            <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Products/illustrations/no_products-x1_ZsaHRDfd8WK.png" alt="No Products" class="table__placeholder__img"
                            srcset="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Products/illustrations/no_products-x1_ZsaHRDfd8WK.png 1x,
                                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Products/illustrations/no_products-x2_v7gXAno1s.png 2x,
                                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Products/illustrations/no_products-x3_pO3ORt4Hj.png 3x,
                                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Products/illustrations/no_products-x4_nzmXICckR.png 4x">
                            <div class="table__placeholder__guide">
                                <h2 class="table__placeholder__guide__header bold">Oh! You haven’t added any product for sale yet!</h2>
                                <a href="{% url 'products:add-product' %}" style="text-decoration: none;">
                                    <button class="primary-btn subtitle bold">Add Product
                                        <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Design_System/Icons/Buttons/add_product_icon_YYLwT5YiFK1.png" alt="Add">
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <tbody>
                        {% for product in products %}
                            <tr class="products__table__row">
                                <td class="product__table__cell">
                                    <label class="checkbox">
                                        <input type="checkbox" id="id_select_{{ forloop.counter0 }}"  class="js-select-btn" name="select" data-product="{{ product.name }}" value="{{ product.id }}">
                                        <span class="checkmark checkmark__small"></span>
                                    </label>
                                </td>
                                <td class="product__table__cell subtitle bold">{{ product.name }}</td>
                                <td class="product__table__cell subtitle">{% if product.is_made_to_order %}Made to Order{% else %}{{ product.stock }}{% endif %}</td>
                                <td class="product__table__cell subtitle">{{ product.sold }}</td>
                                <td class="product__table__cell">
                                    <div class="button-wrapper">
                                        <label class="switch">
                                            {% if product.active %}
                                                <input type="checkbox" name="toggle_availability" class="js-switch-btn" id="id_switch_{{ forloop.counter0 }}" value="{{ product.id }}" checked>
                                            {% else %}
                                                <input type="checkbox" name="toggle_availability" class="js-switch-btn" id="id_switch_{{ forloop.counter0 }}" value="{{ product.id }}">
                                            {% endif %}
                                            <span class="slider round"></span>
                                        </label>
                                    </div>
                                </td>
                                <td class="product__table__cell">
                                    <a href="{% url 'products:update-product' product.id %}" class="tertiary-btn subtitle bold" 
                                    style="text-decoration: none;">Edit Product</a>
                                    <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Products/u_ellipsis-v_d_ZCjBl8H.png" 
                                    alt="Ellipsis" class="product__ellipsis" id="js-product-options-btn-{{forloop.counter0}}">
                                    <div class="product__option--settings" id="js-product-options-modal-{{forloop.counter0}}">
                                        <a href="{% url 'products:duplicate-product' product.id %}" class="profile__pic--settings__link">
                                            <div class="profile__pic--settings__option bold">Duplicate</div>
                                        </a>
                                        <div class="profile__pic--settings__link js-open-delete-modal" data-id="{{ product.id }}" data-product="{{ product.name }}">
                                            <div class="profile__pic--settings__option bold logout">Delete</div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
                <div class="modal__container" id="js-delete-products-modal">
                    <div class="modal__card__wrapper" style="max-width: 338px;">
                        <img 
                            src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Settings/Account_Settings/modal_x_20oKHfTKy.png" 
                            alt="Exit Modal" class="modal__exit__btn js-modal-exit-btn"
                        />
                        <div class="modal__card__header">
                            <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Settings/Account_Settings/modal__alert-circle_vCjlPyZv134.png" alt="Alert">
                        </div>
                        <div class="modal__form__content" style="min-width: 100%; align-items: center;">
                            <h1 class="body-big bold" style="text-align: center;" id="js-delete-text">Are you sure you want to delete these items?</h1>
                            <p style="margin-top: 0.5rem; text-align: center;">This will permanently remove the item from your order form.</p>
                        </div>
                        <div class="modal__form__content modal__form__content-row">
                            <button class="secondary-btn subtitle bold js-modal-exit-btn">Cancel</button>
                            <button class="primary-btn warning subtitle bold" id="js-delete-selected-btn">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}


{% extends 'quicklink/app.html' %}
{% load static %}
{% load imagekit %}

{% block pagetitle %}Total Revenues{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/finances/finances.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}

{% block maincontent %}
    <div class="finances__container">
        <div class="finances__wrapper">
            <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Illustrations/finance-illustration-5x_-EPuaHL7pmP.png"
            alt="Finance Placeholder"
            srcset="
                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Illustrations/finance-illustration-x1_FK7LKjqet.png 1x,
                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Illustrations/finance-illustration-x2_aZVUx4L5iUI.png 2x,
                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Illustrations/finance-illustration-x3_7uablwbhL.png 3x,
                https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Illustrations/finance-illustration-x4_WMnj37onx.png 4x,">
            <h3 class="finances_placeholder_text bold">Coming soon! Stay tuned.</h3>
        </div>
    </div>
{% endblock %}

templates/finances/revenue.html
{% extends 'quicklink/app.html' %}
{% load static %}
{% load hosts %}
{% load imagekit %}
{% load humanize %}
{% load finances %}

{% block pagetitle %}Finances{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static '/css/finances/finances.css' %}">
{% endblock %}

{% block maincontent %}
<div class="finances__container">
    <div class="finances__header">
        <div class="finances__header__wrapper">
            <h1 class="finances__header__wrapper__text extra-bold">Total Revenue</h1>
            <div class="finances__cards">
                <div class="finances__card">
                    <div class="finances__card__content">
                        <h3 class="finances__card__content__title bold">Total Expected Revenue</h3>
                        {% with revenue=total_revenue|floatformat:2 %}
                            <p class="finances__card__content__total header extra-bold">Php {{ revenue|intcomma }}</p>
                        {% endwith %}
                        <div class="finances__card__content__row">
                            <p class="subtitle">This is the complete total revenue you have.</p>
                        </div>
                    </div>
                </div>
                <div class="finances__card">
                    <div class="finances__card__content">
                        <h3 class="finances__card__content__title bold">Payments Received</h3>
                        {% with received=payments_received|floatformat:2 %}
                            <p class="finances__card__content__total header extra-bold">Php {{ received|intcomma }}</p>
                        {% endwith %}
                        <div class="finances__card__content__row">
                            <p class="subtitle">These are the payments you have successfully received.</p>
                        </div>
                    </div>
                </div>
                <div class="finances__card">
                    <div class="finances__card__content">
                        <h3 class="finances__card__content__title bold">Payments Receivable</h3>
                        {% with to_receive=receivables|floatformat:2 %}
                            <p class="finances__card__content__total header extra-bold">Php {{ to_receive|intcomma }}</p>
                        {% endwith %}
                        <div class="finances__card__content__row">
                            <p class="subtitle">These payments are still being processed.</p>
                        </div>
                    </div>
                </div>
            </div>           
        </div>
    </div>

    <div class="finances__list">
        <div class="finances__wrapper">
            <table class="finances__table" id="js-finances-table">
                <thead>
                    <tr class="finances__table__header" id="js-normal-table-header">
                        <th class="finances__table__cell overline bold">Date of Order
                            <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Orders/fi_chevron-down_V5AWvLbdy.svg" class="sort-chevron" id="js-sort-chevron-1" alt="Sort">
                        </th>
                        <th class="finances__table__cell overline bold">Order Number
                            <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Orders/fi_chevron-down_V5AWvLbdy.svg" class="sort-chevron" id="js-sort-chevron-1" alt="Sort">
                        </th>
                        <th class="finances__table__cell overline bold">Checkout</th>
                        <th class="finances__table__cell overline bold">Fees (4%)</th>
                        <th class="finances__table__cell overline bold">Net Total</th>
                        <th class="finances__table__cell overline bold">Payment Status</th>
                    </tr>
                </thead>
            {% if not orders %}
            </table>
                <div class="table__placeholder__container">
                    <div class="table__placeholder__wrapper">
                        <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Illustrations/finance-illustration-x1_FK7LKjqet.png" alt="No Finances" class="table__placeholder__img"
                        srcset="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Illustrations/finance-illustration-x1_FK7LKjqet.png 1x,
                            https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Illustrations/finance-illustration-x2_aZVUx4L5iUI.png 2x,
                            https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Illustrations/finance-illustration-x3_7uablwbhL.png 3x,
                            https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Illustrations/finance-illustration-x4_WMnj37onx.png 4x">
                        <div class="table__placeholder__guide">
                            <h2 class="table__placeholder__guide__header bold">Whoops! You haven’t sold anything yet through QuickLink!</h2>
                            <a href="{% url 'products:products' %}" style="text-decoration: none;">
                                <button class="primary-btn subtitle bold">See my products
                                    <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Icons/white-arrow-right_u2XosdD52.svg" alt="Go">
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            {% else %} 
                <tbody>
                    {% for order in orders %} 
                        <tr class="finances__table__row">
                            <td class="finances__table__cell subtitle">
                                <!-- {{ order.order_date|date:"M d, Y" }} -->
                                <div class="finances__datetime__container">
                                    <div class="finances__datetime__wrapper">
                                        <p class="subtitle">{{ order.order_date|date:"M d, Y" }}</p>
                                        <p class="subtitle subtext">{{ order.order_date|time:"h:i A" }}</p>
                                    </div>
                                </div>
                            </td> 
                            <td class="finances__table__cell subtitle">
                                <a class="table__link subtitle bold" href="{% host_url 'order-invoice' order_id=order.id host 'shops' %}" target="_blank">
                                    <!-- {{ order.get_table_id }} --> {{ request.user.get_initials }}{% if order.id < 10 %}00{% elif order.id <= 100 %}0{% endif %}{{ order.id }}
                                </a>
                            </td>
                            <td class="finances__table__cell subtitle">PHP {{ order|get_checkout }}</td>
                            {% with fees=order|get_fees %}
                                <td class="finances__table__cell subtitle {% if order.fees != 0 %}customer{% else %}merchant{% endif %}">PHP {% if order.fees != 0 %}{{ order.fees|floatformat:2 }}{% else %}{{ fees|floatformat:2 }}{% endif %}</td> 
                            {% endwith %}
                            {% with total=order|get_total %}
                                <td class="finances__table__cell subtitle bold">PHP {% if order.fees != 0 %}{{ order.subtotal|floatformat:2 }}{% else %}{{ total|floatformat:2 }}{% endif %}</td>
                            {% endwith %}
                            <td class="finances__table__cell subtitle">
                                <div class="status-container">
                                    {% if order.payment_status == "PENDING" %}
                                        <div class="payment__status pending overline">
                                    {% elif order.payment_status == "PROCESSING" %}
                                        <div class="payment__status processing overline">
                                    {% else %}
                                        <div class="payment__status received overline">
                                    {% endif %}
                                            {{ order.payment_status }}
                                        </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
        <!-- <div class="finance__footer__wrapper">
            <div class="finance__footer__pagination">
                <a href="" class="finance__footer__pagination__text subtitle" style="color: var(--primary-main); padding: 0 1rem 0 0;">
                    <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Icons/purple-chevron-left_wBy9VjWmK.svg" alt="Left Arrow">
                    Previous
                </a>
                <a href="" class="finance__footer__pagination__circle finance__footer__pagination__circle--active body-big bold">1</a>
                <a href="" class="finance__footer__pagination__circle body-big bold">2</a>
                <a href="" class="finance__footer__pagination__circle  body-big bold">3</a>
                <a href="" class="finance__footer__pagination__text subtitle" style="color: var(--primary-main); padding: 0 0 0 1rem;">
                    Next
                    <img src="https://ik.imagekit.io/ripzjge77zz/Quicklink_App/Merchant/Finances/Icons/purple-chevron-right_5n0Ptn0aO.svg" alt="Left Arrow">
                </a>
            </div>    
        </div>  -->
    </div>
</div>
{% endblock %}

{% block scriptsBody %}
    <!-- Tablesorter lightweight JQuery plugin — See docs for more info: https://mottie.github.io/tablesorter/docs/-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/jquery.tablesorter.min.js" integrity="sha512-qzgd5cYSZcosqpzpn7zF2ZId8f/8CHmFKZ8j7mU4OUXTNRd5g+ZHBPsgKEwoqxCtdQvExE5LprwwPAgoicguNg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/jquery.tablesorter.widgets.min.js" integrity="sha512-dj/9K5GRIEZu+Igm9tC16XPOTz0RdPk9FGxfZxShWf65JJNU2TjbElGjuOo3EhwAJRPhJxwEJ5b+/Ouo+VqZdQ==" crossorigin="anonymous"></script>
    <script>
        $(function() {
            $("#js-finances-table").tablesorter({ sortList: [[1,0], [2,0]], selectorSort : 'img' });
            var chevrons = $(".sort-chevron");
            chevrons.each(function() {
                $(this).click(function(e) {
                    if (e.shiftKey) {
                        $(this).toggleClass("reverse");
                    } else {
                        var clicked = $(this).attr("id");
                        chevrons.each(function() {
                            if ($(this).attr("id") != clicked) {
                                $(this).removeClass("reverse");
                            }
                        });
                        $(this).toggleClass("reverse");
                    }
                })
            });
        });
    </script>
{% endblock %}