apps/customers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.marketplace, name='marketplace'),
    path('shop/<str:username>/', views.view_products, name='view-products'),
    path('shop/<str:username>/<str:product_pk>/', views.add_order, name='add-order'),
    path('shop/<str:username>/<str:item_pk>/edit/', views.edit_order, name='edit-order'),
    path('update-cart-item/', views.update_item, name='update-item'),
    path('checkout/<str:order_id>/', views.checkout, name='checkout'),
    path('checkout/<str:order_id>/payment/<str:slug>/', views.payment, name='payment'),
    path('checkout/<str:order_id>/payment/bank/failed-linking/', views.failed_bank_linking, name='failed-bank-linking'),
    path('checkout/<str:order_id>/payment/bank/account-linking/', views.bank_account_linking, name='bank-account-linking'),
    path('checkout/<str:order_id>/payment/bank/pay/', views.bank_transfer_payment, name='bank-payment'),
    path('checkout/<str:order_id>/payment/bank/pay/otp/', views.bank_transfer_otp, name='payment-otp'),
    path('checkout/complete/<str:order_id>/', views.order_completion, name='order-completion'),
    path('checkout/invoice/<str:order_id>/', views.order_invoice, name='order-invoice'),
    path('register/', views.account_creation, name='register'),
    path('login/', views.customer_login, name='login'),
    path('logout/', views.customer_logout, name='logout'),
    path('register/verification/<str:user_id>/', views.email_verification, name='email-verification'),
    path('register/confirmation/<uidb64>/<token>/', views.email_confirmation, name='email-confirmation'),
    path('register/information/', views.register_customer_information, name='register-information'),
    path('register/address/', views.register_customer_address, name='register-address'),
    path('register/payment/', views.register_customer_payment, name='register-payment'),
    path('register/payment/<str:slug>/', views.register_customer_payment_method, name='register-payment-method'),
    path('register/notifications/', views.register_customer_notifications, name='register-notifications'),
    path('register/complete/', views.register_complete, name='register-complete'),
    path('orders/', views.account_orders, name='orders'),
    path('reorder/<str:order_id>/', views.reorder, name='reorder'),
    path('load_cities/', views.load_cities, name='load-cities'),
    path('ewallet-callback/', views.ewallet_callback, name='ewallet-callback')
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.LOCAL_DEV:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

handler400 = 'accounts.views.handler_400'
handler403 = 'accounts.views.handler_403'
handler404 = 'accounts.views.handler_404'
handler500 = 'accounts.views.handler_500'

apps/orders/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.orders, name='order-summary'),
    # path('delete-order/<str:order_pk>/', views.delete_order, name='delete-order'),
    path('pending/', views.pending_orders, name='pending-orders'),
    path('status-change/', views.order_status_change, name='order-status-change'),
    # path('update-change/', views.send_update_change, name="send-update-change")
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
import accounts

# import debug_toolbar

urlpatterns = [
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    path('_nested_admin/', include('nested_admin.urls')),
    # url(r'^hijack/', include('hijack.urls', namespace='hijack')),
    path('accounts/', include('allauth.urls')),
    path('avatar/', include('avatar.urls')),
    path('', include(('accounts.urls', 'accounts'), namespace='users')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('finances/', include(('finances.urls', 'finances'), namespace='finances')),
]

if settings.LOCAL_DEV:
    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    handler400 = 'accounts.views.handler_400'
    handler403 = 'accounts.views.handler_403'
    handler404 = 'accounts.views.handler_404'
    handler500 = 'accounts.views.handler_500'

apps/orders/views.py
import os
import environ
from django.conf import settings

from django.shortcuts import render, redirect
from django.utils import timezone
from django.utils.timezone import datetime, timedelta
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.views.decorators.cache import cache_control

from .services import *
from .forms import PreviewOrderForm, OrderForm
from .filters import OrderFilter, PendingOrderFilter
from products.models import Product, Size, Addon
from orders.models import Order, OrderItem
from accounts.decorators import setup_required, allowed_users
from accounts.models import *

from django.http import HttpResponse, JsonResponse
from decimal import Decimal
import json

import openpyxl

from os import path
from datetime import datetime

from django.core.paginator import Paginator
from django.core import serializers

import vonage

# Create your views here.

# Change Order Status
def order_status_change(request):
    data = request.GET.copy()
    order_ids = request.GET.getlist("orders[]")
    status = data.get("status", "")
    orders = Order.objects.filter(id__in=order_ids)
    orders.update(order_status=status)

    if len(order_ids) > 1:
        shop_info = User.objects.select_related("shop_info").get(pk=request.user.pk)
        shop_info.can_send_updates = True
        shop_info.save()

    res = serializers.serialize('json', list(orders), fields=("id", "order_status"))
    return JsonResponse(data=res, safe=False)

# def send_update_change(request):
#     shop_info = User.objects.select_related("shop_info").get(pk=request.user.pk)
#     shop_info.can_send_updates = True
#     shop_info.save()
#     res = serializers.serialize('json', [shop_info, ])
#     return JsonResponse(data=res, safe=False)

# Order Summary
@login_required(login_url='accounts:login')
@setup_required
@allowed_users(allowed_roles=[User.Types.MERCHANT, User.Types.QUICKIES, User.Types.ADMIN])
@cache_page(30)
@cache_control(private=True)
def orders(request):
    user = request.user
    can_send_updates = user.shop_info.can_send_updates
    data = request.GET.copy()
    orderFilter = OrderFilter(data, request=request)
    orders = orderFilter.qs

    search_query = request.GET.get('search', None)

    if search_query:
        orders = orders.filter( 
            Q(id__icontains=search_query) |
            Q(order_information__session_sender__customer_name__icontains=search_query) |
            Q(order_status__icontains=search_query) |
            Q(payment_status__icontains=search_query)
        )

    current_time = datetime.now()
    file_date = current_time.strftime('%m%d%y')

    shop_name = user.shop_info.slugify_name
    file_name = "QL_" + shop_name + "_order_summary_" + str(file_date)

    if request.method == "POST":
        if "send_customer_updates" in request.POST:
            last_update = user.shop_info.update_status_changed
            update_orders = Order.objects.filter(shop=user, complete=True, order_status_changed__gte=last_update)

            send_customer_updates(request, update_orders)

            shop_info = user.shop_info
            shop_info.can_send_updates = False
            shop_info.save()

    context = {'orders':orders, 'orderFilter':orderFilter, "file_name":file_name, "can_send_updates": can_send_updates, "search_query":search_query}
    return render(request, 'orders/order_summary.html', context)

# Orders -- Order Filter (shop=request.user)

# Total Expected Revenue
# total_revenue = 0
# for order in orders:
#   total_revenue += order.total

# Payments Received
# received_orders = Order.objects.filter(shop=request.user, payment_status="RECEIVED")
# payments_received = 0
# for order in received_orders
#   payments_received += order.total

# Payments Receivables
# receivable_orders = Order.objects.filter(shop=request.user).exclude(payment_status="RECEIVED")
# receivables = 0
# for order in receivable_orders
#   receivables += order.total

# context = {"orders":orders, "total_revenue":total_revenue, "payments_received":payments_received, "receivables":receivables}
# {% for order in orders %}
# {{ total_revenue }}
# {{ payments_received }}
# {{ receivables }}

# Pending Orders
@login_required(login_url='accounts:login')
@setup_required
@allowed_users(allowed_roles=[User.Types.MERCHANT, User.Types.QUICKIES, User.Types.ADMIN])
@cache_page(30)
@cache_control(private=True)
def pending_orders(request):
    # Get merchant user
    user = request.user

    # Get initial value for filter set (Alphabetical Order)
    productChoices = Product.objects.filter(user=user).order_by('name')
    if len(productChoices) > 0:
        product = Product.objects.filter(user=user).first()
    else:
        product = None
    
    # Set initial data
    delivery_date = timezone.localdate()
    data = request.GET.copy()
    data.setdefault('product', None)
    data.setdefault('delivery_date', delivery_date)

    # Get pending orders
    orders = Order.objects.filter(shop=user, complete=True)
    orders = orders.filter(Q(order_status="PENDING") | Q(order_status="PREPARING"))
    
    # Get pending product orders
    order_items = OrderItem.objects.filter(order__in=orders).order_by('product')

    # Product filter form
    pendingFilter = PendingOrderFilter(data, request=request, queryset=order_items)
    items = pendingFilter.qs

    if pendingFilter.get_product:
        sizes = Size.objects.filter(product=pendingFilter.get_product)
        addons = Addon.objects.filter(product=pendingFilter.get_product)
    else:
        sizes = None
        addons = None

    if data.get("delivery_date"):
        try:
            date = data.get("delivery_date").strftime('%m%d%y')
        except:
            date = datetime.strptime(data.get("delivery_date"), '%Y-%m-%d').strftime('%m%d%y')
    else:
        date = datetime.now().strftime('%m%d%y')

    shop_name = user.shop_info.slugify_name

    if data.get("product"):
        id = data.get("product")
        product_name = Product.objects.get(id=id)
        product_name = product_name.name
        product_name = product_name.replace(" ", "_").lower()
        file_name = "QL_" + shop_name + "_pending_" + product_name + "_" + str(date)
    else:
        file_name = "QL_" + shop_name + "_pending_orders_" + str(date)
    
    context = {
        'product':product,
        'orders':orders,
        'order_items':order_items,
        'pendingFilter':pendingFilter,
        'items':items,
        'sizes':sizes, 
        'addons':addons,
        "file_name":file_name
    }
    return render(request, 'orders/pending_orders.html', context)

# Deleting Orders (For Testing)
# @login_required(login_url='accounts:login')
# @setup_required
# @allowed_users(allowed_roles=[User.Types.MERCHANT, User.Types.QUICKIES, User.Types.ADMIN])
# def delete_order(request, order_pk):
#     order = Order.objects.get(id=order_pk)
#     if request.method == "POST":
#         order.delete()
#         return redirect('/shop/orders/')

#     context = {'order':order}
#     return render(request, 'orders/delete_order.html', context)

templates/orders/available_products.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static '/css/customer-products.css' %}">
    <link rel="stylesheet" href="{% static '/css/datetime.css' %}">
    <script src="{% static '/js/datetime.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>

<body onload="realtimeClock()">
    <div class="header-container">
        <div class="header-content">
            <div class="datetime" id="datetime"></div>
        </div>
    </div>

    {% include 'quicklink/navbar.html' %}
    
    <main>
        <div class="user-products-container">
            <div class="user-products-wrapper">
                <div class="prototype">
                    <div class="prototype-wrapper">
                        <div class="iphone">
                            <div class="power"></div>
                            <div class="lock"></div>
                            <div class="volume up"></div>
                            <div class="volume down"></div>
                            <div class="camera"></div>
                            <div class="speaker"></div>
                            <div class="screen">
                                <img src="{% static 'media/prototype/header.png' %}" alt="">
                                <div class="screen-content">
                                    <img src="{% static 'media/prototype/mobile-nav.png' %}" alt="">
                                    <div class="screen-content-products-container">
                                        <div class="screen-content-products-wrapper">
                                            {% for product in products %}
                                            <a href="{% url 'orders:add-order' product.id %}" class='product-card-link'>
                                                <span class="product-card">
                                                    <img src="{{ product.image }}" alt="" class="product-card-img">
                                                    <h1 class="subtitle bold">{{ product.name }}</h1>
                                                    <p class="overline">PHP {{ product.price }} </p>
                                                </span>
                                            </a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                                <img src="{% static 'media/prototype/footer.png' %}" alt="">
                            </div>
                            <div class="phone-button">
                                <div class="square"></div>
                            </div>
                        </div>
                      </div>
                </div>
            </div>
        </div>
    </main>
</body>
</html>

templates/orders/delete_order.html
{% extends 'quicklink/base.html' %}

{% block pagetitle %}Delete Order{% endblock %}

{% block maincontent %}

<div class="empty-products-container">
    <div class="empty-products-wrapper">
        <div class="empty-products-content">
            <div class="empty-products-text">
                <h1>Are you sure you want to delete Order {{ order.id }}?</h1>
                <form action="{% url 'orders:delete-order' order.id %}" method="POST">
                    {% csrf_token %}
                    <a href="{% url 'orders:order-summary' %}">Cancel</a>
                    <input type="submit" value="Confirm">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/orders/order_form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static '/css/customer-products.css' %}">
    <link rel="stylesheet" href="{% static '/css/datetime.css' %}">
    <script src="{% static '/js/datetime.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>

<body onload="realtimeClock()">
    <div class="header-container">
        <div class="header-content">
            <div class="datetime" id="datetime"></div>
        </div>
    </div>

    {% include 'quicklink/navbar.html' %}
    
    <main>
        <div class="user-products-container">
            <div class="user-products-wrapper">
                <div class="prototype">
                    <div class="prototype-wrapper">
                        <div class="iphone">
                            <div class="power"></div>
                            <div class="lock"></div>
                            <div class="volume up"></div>
                            <div class="volume down"></div>
                            <div class="camera"></div>
                            <div class="speaker"></div>
                            <div class="screen">
                                <img src="{% static 'media/prototype/header.png' %}" alt="">
                                    <div class="screen-content">
                                        <form method="post">
                                        <img src="{% static 'media/prototype/mobile-nav.png' %}" alt="">
                                        <div class="screen-content-order-container">
                                            <div class="screen-content-order-wrapper">
                                                <img src="{% static 'product.image.url' %}" class='product-image'>

                                                <div class="order-product-description">
                                                    <h3 class='bold'>{{ product.name }}</h3>
                                                    <p class='product-description'>{{ product.description }}</p>
                                                    {% if product.stock == "Made to Order" %}
                                                        <p class='product-stock'>{{ product.stock }}</p>
                                                    {% else %}
                                                        <p class='product-stock'>Stocks available: {{ product.stock }}</p>
                                                    {% endif %}
                                                    <p class='product-instructions'>Possible allergens: {{ product.instructions }}</p>
                                                </div>
                                                
                                                <div class="order-product-size">
                                                    <h2 class='subtitle bold'>Size/Type</h2>
                                                    {% for size in sizes %}
                                                        <div class="order-product-size-input">
                                                            <label class="radio-mobile">
                                                                <input type="radio">
                                                                <span class="radio-select-mobile"></span>
                                                            </label>
                                                            <label for="size" class='subtitle product-size'>{{ size.size }} (PHP {{ size.price_size }})</label>
                                                        </div>
                                                    {% endfor %}
                                                </div>
                                                
                                                {% if not addons %}
                                                {% else %}
                                                    <div class="order-product-addons">
                                                        <h2 class='subtitle bold'>Add-Ons</h2>
                                                        {% for addon in addons %}
                                                            <div class="order-product-addon">
                                                                <div class="order-product-addons-input">
                                                                    <label class="checkbox-mobile">
                                                                        <input type="checkbox">
                                                                        <span class="checkmark-mobile"></span>
                                                                    </label>
                                                                    <label for="addon" class='subtitle product-addon'>{{ addon.addon }}</label>
                                                                </div>
                                                                <span class="addon-price">+ PHP {{ addon.price_addon }}.00</span>
                                                            </div>
                                                        {% endfor %}
                                                    </div>
                                                {% endif %}
                                                

                                                <div class="order-product-instructions">
                                                    <h2 class='subtitle bold'>Special Instructions</h2>
                                                    <textarea class="mobile-large-input default subtitle" 
                                                        placeholder="Leave us a note! (Optional)"
                                                        style="color:#000;"></textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="order-products-footer">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <input type="submit" value="Add Product" class="add-to-basket-btn subtitle bold">
                                        </form>
                                    </div>
                                <img src="{% static 'media/prototype/footer.png' %}" alt="">
                            </div>
                            <div class="phone-button">
                                <div class="square"></div>
                            </div>
                        </div>
                      </div>
                </div>
            </div>
        </div>
    </main>
</body>
</html>
        